# Generated by Django 5.0.3 on 2024-03-25 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_companyprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='description',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='other_information',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='title',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_name',
            field=models.CharField(default='Unnamed Company', max_length=100),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='description',
            field=models.TextField(default='unnamed'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='job_listings', to='job.companyprofile'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='job_description',
            field=models.TextField(default='Description'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='job_title',
            field=models.CharField(default='Job Title', max_length=100),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='company_benefits',
            field=models.TextField(default='Company Benefits'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='desired_qualifications',
            field=models.TextField(default='Desired Qualifications'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='employment_type',
            field=models.CharField(default='Employment Type', max_length=100),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='location',
            field=models.CharField(default='Location', max_length=100),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='required_qualifications',
            field=models.TextField(default='Required Qualifications'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='responsibilities',
            field=models.TextField(default='Responsibilities'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='salary_range',
            field=models.CharField(default='Salary Range', max_length=100),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField()),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('job_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='job.joblisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
