# Generated by Django 5.0.3 on 2024-03-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_jobapplication_profile_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('job_seeker', 'Job Seeker'), ('company_user', 'Company User'), ('admin', 'Admin')], max_length=20),
        ),
    ]
