# Generated by Django 5.0.3 on 2024-03-25 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_joblisting_job_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobListing',
        ),
    ]
