# Generated by Django 5.0.3 on 2024-03-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_delete_companyprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(default='', upload_to='resumes/'),
        ),
    ]
